beatyrec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),

    # path('__debug__/', include('debug_toolbar.urls')),

]

home/urls.py
from django.urls import path, include
from . import views

app_name = "home"   


urlpatterns = [
    path("you/", views.detailView, name="detail"),
    path("you/upload/", views.uploadView, name="upload"),
    # path("upload/", views.uploadView, name="upload"),
    path("", views.homeView, name="homepage"),
    ]   

home/models.py
from django.db import models

# Create your models here.

beatyrec/home/views.py
from django.shortcuts import render
from .script.main import skinUnderTone, fileNameExtract
from django.http import HttpResponse, JsonResponse

# Create your views here.
def detailView(request):
    context = {

    }
    return render(request, "you.html", context=context)
def homeView(request):

    context = {

    }
    
    return render(request, "home.html", context=context)


def uploadView(request):
    if request.method == 'POST':
        print("POSTED")
        # print(request.POST)
        filename = 'home/static/uploaded.jpg' 
        try:
            data = request.POST["file"]
            import base64
            data = data[len("data:image/png;base64"):]
            imgdata = base64.b64decode(data) 
            filename = 'home/static/uploaded.jpg' 
            with open(filename, 'wb') as f:
                f.write(imgdata)
                print("file saved")
        except:
            passedFiles = request.FILES.get('file')
            print(request)
            print(passedFiles)
            filePath = f'home/static/uploaded.jpg'
            with open(filePath, 'wb+') as destination:
                for chunk in passedFiles.chunks():
                    destination.write(chunk)
        
        result, faceFount = skinUnderTone(filename, 'home/static/debug.jpg')
        print(result, faceFount)
        if faceFount: 
            displayImg = "home/static/userview.jpg"
        else:
            displayImg = "home/static/userview.jpg"

        # code:
        # -1, no skin detected
        # 0, cool tone
        # 1, neutral tone
        # 2, warm tone
        hasSkin = True
        foundation = None
        if result == 0:
            foundation = "Cool"
            plts = [
                "#FFC5DE",
                "#F8A2AA",
                "#E3237B",
                "#A92D7B",
                "#89112C",
                "#6B0F34",
            ]
        elif result == 1:
            foundation = "Neutral"
            plts = [
                "#FFC5DE",
                "#F8A2AA",
                "#E3237B",
                "#A92D7B",
                "#89112C",
                "#6B0F34",
                "#FECBC8",
                "#FCA590",
                "#DE4C30",
                "#D62C1D",
                "#A10314",
                "#8E131D",
            ]
        elif result == 2:
            foundation = "Warm"
            plts = [
                "#FECBC8",
                "#FCA590",
                "#DE4C30",
                "#D62C1D",
                "#A10314",
                "#8E131D",
            ]
        else:
            hasSkin = False
            foundation = "No Skin Detected"


    context = {
        "displayImg": displayImg,
        "foundation": foundation,
        "hasSkin": hasSkin,
        "result": result,
        "fileName": fileNameExtract(displayImg),
        "color": "#F0A1FB",
        "plts": plts,
        
    }
    
    response = HttpResponse()
    response['displayImg'] = displayImg
    response['foundation'] = foundation
    response['hasSkin'] = hasSkin
    return JsonResponse(context)

home/views.py
from django.shortcuts import render
from .script.main import skinUnderTone, fileNameExtract
from django.http import HttpResponse, JsonResponse

# Create your views here.
def detailView(request):
    context = {

    }
    return render(request, "you.html", context=context)
def homeView(request):

    context = {

    }
    
    return render(request, "home.html", context=context)


def uploadView(request):
    if request.method == 'POST':
        print("POSTED")
        # print(request.POST)
        filename = 'home/static/uploaded.jpg' 
        try:
            data = request.POST["file"]
            import base64
            data = data[len("data:image/png;base64"):]
            imgdata = base64.b64decode(data) 
            filename = 'home/static/uploaded.jpg' 
            with open(filename, 'wb') as f:
                f.write(imgdata)
                print("file saved")
        except:
            passedFiles = request.FILES.get('file')
            print(request)
            print(passedFiles)
            filePath = f'home/static/uploaded.jpg'
            with open(filePath, 'wb+') as destination:
                for chunk in passedFiles.chunks():
                    destination.write(chunk)
        
        result, faceFount = skinUnderTone(filename, 'home/static/debug.jpg')
        print(result, faceFount)
        if faceFount: 
            displayImg = "home/static/userview.jpg"
        else:
            displayImg = "home/static/userview.jpg"

        # code:
        # -1, no skin detected
        # 0, cool tone
        # 1, neutral tone
        # 2, warm tone
        hasSkin = True
        foundation = None
        if result == 0:
            foundation = "Cool"
            foundation = "Cool"
            plts = [
                "#FFC5DE",
                "#F8A2AA",
                "#E3237B",
                "#A92D7B",
                "#89112C",
                "#6B0F34",
            ]
        elif result == 1:
            foundation = "Neutral"
            plts = [
                "#FFC5DE",
                "#F8A2AA",
                "#E3237B",
                "#A92D7B",
                "#89112C",
                "#6B0F34",
                "#FECBC8",
                "#FCA590",
                "#DE4C30",
                "#D62C1D",
                "#A10314",
                "#8E131D",
            ]
        elif result == 2:
            foundation = "Warm"
            plts = [
                "#FECBC8",
                "#FCA590",
                "#DE4C30",
                "#D62C1D",
                "#A10314",
                "#8E131D",
            ]
        else:
            hasSkin = False
            foundation = "No Skin Detected"
            plts =[]


    context = {
        "displayImg": displayImg,
        "foundation": foundation,
        "hasSkin": hasSkin,
        "result": result,
        "fileName": fileNameExtract(displayImg),
        "color": "#F0A1FB",
        "plts": plts,
        
    }
    
    response = HttpResponse()
    response['displayImg'] = displayImg
    response['foundation'] = foundation
    response['hasSkin'] = hasSkin
    return JsonResponse(context)

beatyrec/home/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      File Inspection
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block stylesheets %}
    {% endblock stylesheets %}
  </head>
  
  
  <body style="background-color: rgba(249, 225, 226, 1);">
    {% block content %} {% endblock content %}
  </body>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
  {% block javascripts %}
  {% endblock javascripts %}
  
</html>

beatyrec/home/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %} 
    <div class="container">
        <div class="row ">
            <div class="buttondiv">
                <button type="button" class="btn" style="background-color: #F5BDC1; border-radius: 20px; ">
                    <a href="{% url 'home:detail' %}">Get Start</a>
                    </button>
            </div>
        </div>
        
        <div class="row mt-3">
            <div class="card p-5" style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                <div class="text mt-3" style="color: white;">
                     <h1 class ="display-2 head" > <strong>Welcome yourPalette!</strong> 💄💋</h1> 

                    <text class="display-6 font-weight-normal">Experience beauty made just for you with yourPalette. Simply upload a
                        photo and discover a curated selection of foundation, brow and lip
                        shades that perfectly match your undertone. Effortlessly elevate your
                        makeup routine with personalized recommendations, exclusively tailored
                        to your unique beauty needs. Join us today and unveil your perfect
                        palette!&quot;</text>
                    </div>
            </div>
        </div>

        <div class="row mt-5 me-1 mx-auto">
            <div class="card3 mx-auto p-3" style="height:auto; border-radius: 20px; background-color: #F5BDC1;">
                <div class="text text-center display-4 float-center m-auto" style="color: white;  ">So How Does It Work? 🤔</div>
            </div>
        </div>

        <div class="row mt-5 justify-content-around">
                <div class="col-3 p-3" style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                    <div class="h2 rigthside "><u> Step 1</u> </div>
                    <text class="h4">
                        Take a selfie! 🤳 Capture a stunning full-face selfie, ensuring your head is in frame
                        and lit with white light to showcase your natural beauty.
                    </text>
                    <img src="{% static 'img1.jpg' %}" width=60% 
                        height=50% class="rounded" style="display: block;">
                        <p> Like this !</p>
                </div>
                <div class="col-3 p-3" style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                    <text class="h4">
                       OR, snap a picture of your wrist up close, with the flash on, for optimal clarity. 
                    </text>
                    <img src="{% static 'img2.jpg' %}" width=60% 
                        height=50% class="rounded m-4" style="display: block;">
                        <p> Like this !</p>
                </div>
            <div class="col-3 justify-content-around "style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                <div class="mt-2" style="color: black; font-size: 30px"><p display-6><u>Step 2</u></p>
                    <p>Upload your selfie/image of your wrist and we will start working on your palette! 🎨 
                    </p></div>
            </div> 
        </div>

        <div class="row mt-5 ">
            <div class="card4 p-3" style="height:auto; border-radius: 50px; background-color: #F5BDC1;">
                    <div class="text h2">
                        <u>Step 3</u>
                    </div>
                    <text class="display-6">Voila! 🤩 
                        Your own color palette awaits. It may look something like this...
                    </text>
                    <img src="{% static 'img2.jpg' %}" width=60% 
                    height=50% class="rounded m-4 float-center mx-auto" style="display: block;">
            </div>
        </div>
    </div>
    <div class="row mt-3 ms-5 ps-5">
        <div class="buttondiv">
            <button type="button" class="btn" style="background-color: #F5BDC1; border-radius: 20px; ">
                <a href="{% url 'home:detail' %}">I am ready to find my palette 😎</a>
                </button>
        </div>
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>



      <!-- <video id="video" width="640" height="480" autoplay></video>
      <button id="snap">Take Picture</button>
      <canvas class="d-none" id="canvas" width="640" height="480"></canvas>
      <div>
        <form class="p-2" style="z-index: 1;" method="post" enctype="multipart/form-data" id="file_form">
            {% csrf_token %}
            <div class="input-group">
                <input class="form-control" type="file" id="file" name="file" placeholder="Upload File" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-secondary" id="myBtn">Upload</button>
                </div>
            </div>
        </form>
    </div>
      <div class="h1" id="showWords"> -->
        <!-- <img src="{% static 'debug.jpg' %}"> -->
      <!-- </div> -->
      <!-- <div class="row" id="showImg"> -->
        <!-- <img src="{% static 'debug.jpg' %}"> -->
      <!-- </div> -->
      
{% endblock content %}






	
</body>
</html>

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      yourPalette
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block stylesheets %}
    {% endblock stylesheets %}
  </head>
  
  
  <body style="background-color: rgba(249, 225, 226, 1);">
    {% block content %} {% endblock content %}
  </body>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
  {% block javascripts %}
  {% endblock javascripts %}
  
</html>

home/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %} 
    <div class="container">
        <div class="row ">
            <div class="buttondiv">
                <button type="button" class="btn" style="background-color: #F5BDC1; border-radius: 20px; ">
                    <a href="{% url 'home:detail' %}">Get Start</a>
                    </button>
            </div>
        </div>
        
        <div class="row mt-3">
            <div class="card p-5" style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                <div class="text mt-3" style="color: white;">
                     <h1 class ="display-2 head" > <strong>Welcome yourPalette!</strong> 💄💋</h1> 

                    <text class="display-6 font-weight-normal">Experience beauty made just for you with yourPalette. Simply upload a
                        photo and discover a curated selection of foundation, brow and lip
                        shades that perfectly match your undertone. Effortlessly elevate your
                        makeup routine with personalized recommendations, exclusively tailored
                        to your unique beauty needs. Join us today and unveil your perfect
                        palette!&quot;</text>
                    </div>
            </div>
        </div>

        <div class="row mt-5 me-1 mx-auto">
            <div class="card3 mx-auto p-3" style="height:auto; border-radius: 20px; background-color: #F5BDC1;">
                <div class="text text-center display-4 float-center m-auto" style="color: white;  ">So How Does It Work? 🤔</div>
            </div>
        </div>

        <div class="row mt-5 justify-content-around">
                <div class="col-3 p-3" style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                    <div class="h2 rigthside "><u> Step 1</u> </div>
                    <text class="h4">
                        Take a selfie! 🤳 Capture a stunning full-face selfie, ensuring your head is in frame
                        and lit with white light to showcase your natural beauty.
                    </text>
                    <img src="{% static 'img1.jpg' %}" width=60% 
                        height=50% class="rounded" style="display: block;">
                        <p> Like this !</p>
                </div>
                <div class="col-3 p-3" style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                    <text class="h4">
                       OR, snap a picture of your wrist up close, with the flash on, for optimal clarity. 
                    </text>
                    <img src="{% static 'img2.jpg' %}" width=60% 
                        height=50% class="rounded m-4" style="display: block;">
                        <p> Like this !</p>
                </div>
            <div class="col-3 justify-content-around "style="height:auto;background-color: #F5BDC1; border-radius: 20px;">
                <div class="mt-2" style="color: black; font-size: 30px"><p display-6><u>Step 2</u></p>
                    <p>Upload your selfie/image of your wrist and we will start working on your palette! 🎨 
                    </p></div>
            </div> 
        </div>

        <div class="row mt-5 ">
            <div class="card4 p-3" style="height:auto; border-radius: 50px; background-color: #F5BDC1;">
                    <div class="text h2">
                        <u>Step 3</u>
                    </div>
                    <text class="display-6">Voila! 🤩 
                        Your own color palette awaits. It may look something like this...
                    </text>
                    <img src="{% static 'result.png' %}" width=60% 
                    height=60% class="rounded m-4 float-center mx-auto" style="display: block; border-radius: 25px;">
            </div>
        </div>
    </div>
    <div class="row mt-3 ms-5 ps-5">
        <div class="buttondiv">
            <button type="button" class="btn" style="background-color: #F5BDC1; border-radius: 20px; ">
                <a href="{% url 'home:detail' %}">I am ready to find my palette 😎</a>
                </button>
        </div>
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>
    <div class="row mt-3 ms-5 ps-5">
        
    </div>



      <!-- <video id="video" width="640" height="480" autoplay></video>
      <button id="snap">Take Picture</button>
      <canvas class="d-none" id="canvas" width="640" height="480"></canvas>
      <div>
        <form class="p-2" style="z-index: 1;" method="post" enctype="multipart/form-data" id="file_form">
            {% csrf_token %}
            <div class="input-group">
                <input class="form-control" type="file" id="file" name="file" placeholder="Upload File" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-secondary" id="myBtn">Upload</button>
                </div>
            </div>
        </form>
    </div>
      <div class="h1" id="showWords"> -->
        <!-- <img src="{% static 'debug.jpg' %}"> -->
      <!-- </div> -->
      <!-- <div class="row" id="showImg"> -->
        <!-- <img src="{% static 'debug.jpg' %}"> -->
      <!-- </div> -->
      
{% endblock content %}






	
</body>
</html>